### ISSUE TITLE
TypeError: null is not an object (this.settings.containerEl.appendChild / this.settings.containerEl.removeChild)

### ISSUE THREAD

**Issue by mseymour** [imgix/drift#28] opened 2016-05-31 12:06 UTC
With `hoverBoundingBox` and `touchBoundingBox` set to `true`, on hover with the latest version of Drift, I get these error messages, as well as the bounding box not appearing directly over the image:

    [Error] TypeError: null is not an object (evaluating 'this.settings.containerEl.appendChild')
    	show (app-2622524ee1.js:1927)
    	_show (app-2622524ee1.js:2305)
    	_handleEntry (app-2622524ee1.js:2290)
    [Error] TypeError: null is not an object (evaluating 'this.settings.containerEl.removeChild')
    	hide (app-2622524ee1.js:1939)
    	_hide (app-2622524ee1.js:2322)

My current settings:

    current_drift_instance = new Drift(document.querySelector('#photo-tab img'), {
        paneContainer: document.querySelector('.item-status'),
        inlinePane: 768,
        inlineOffsetY: -75,
        zoomFactor: 5,
        hoverBoundingBox: true,
        touchBoundingBox: true
    });

**Comment by paulstraw** [comment] 2016-05-31 16:59
Hmm, I haven't seen this error. Would it be possible for you to set up a reduced test case on codepen.io or similar? That would be a huge help for debugging.

**Comment by mseymour** [comment] 2016-05-31 18:11
Here you go: http://codepen.io/mseymour/pen/YWPWPw

It seems to happen when switching tabs.

**Comment by paulstraw** [comment] 2016-06-07 18:51
Strange. What browser are you seeing this in? I'm not able to replicate it in your CodePen, but there are some strange sizing issues going on there (seems like just a CSS bug though).

**Comment by mseymour** [comment] 2016-06-08 12:49
Latest Safari, 9.1.1 (11601.6.17).

**Comment by paulstraw** [comment] 2016-06-13 18:33
Hey @mseymour, I'm still unable to reproduce this error in Safari. Are there any more steps to making it happen?

**Comment by mseymour** [comment] 2016-06-14 14:04
I don't seem to be having the error anymore, in that case it might've been ordering of code.

Other than that, I've noticed that the bounding box element is outside of the image's parent by 5 elements, so it is not being constrained by the image, but the column that it is in. It also happens to be right next to the element that contains the zoom pane.

**Comment by paulstraw** [comment] 2016-06-14 19:16
As far as the the bounding issue goes, that appears to be something caused by the example's CSS (possibly Bootstrap doing something odd?). If it's possible to set up a reduced test case for that, I'm happy to look into solutions. Going to close this issue now though, since the underlying problem appears to be resolved. Feel free to reopen if you see this issue again!

**Closed by paulstraw** 2016-06-14 19:16 UTC

**Comment by mseymour** [comment] 2016-06-27 15:19
Looking at it again, it seems that I needed to have an element set as `position: relative` due to your use of `offsetParent` on line 27 of Trigger.js, which at least how I understand it looks for the closest parent that uses `position: relative` or `position: absolute`. I did so, but still the bounding box is still being rendered improperly.

It might also be a general layout issue too. I updated my pen from earlier (http://codepen.io/mseymour/pen/YWPWPw) and made it match more or less what my layout and code is set up as, including adding space at the top to mimic the approximate amount of space that the navbar takes up.

**Comment by paulstraw** [comment] 2016-06-30 01:24
I'm still unable to replicate this outside of your pen, unfortunately, which means it may be some sort of conflict with another piece of CSS or JS you're importing. Have you been able to replicate it in a reduced test case? I'm having trouble narrowing down what could be causing this.

**Comment by evenfrost** [comment] 2017-01-11 15:22
Getting same error because of [this line](https://github.com/imgix/drift/blob/735452739d7784c9a1293a9d2b76fb472daf4a0f/src/js/Trigger.js#L27). 
`offsetParent` is somehow set to `null`, though when testing in Chrome dev tools `offsetParent` of image is set properly (and points to its parent).
P.S. Neither of [these cases](http://stackoverflow.com/a/11639664/1800935) are true for me.

**Comment by ezalivadnyi** [comment] 2017-12-13 17:08
Plugin has a bug. When parents is position:relative, it append the hoverBoundingBox no to <body> end, and it's hoverBoundingBox's position is incorrect.
