### ISSUE TITLE
Toggling fullscreen in Chrome breaks zoom/pan

### ISSUE THREAD

**Issue by dw2** [imgix/drift#29] opened 2016-06-10 21:03 UTC
**Mac** Version 10.11.5
**Chrome** Version 51.0.2704.84 (64-bit)

**To reproduce:**
 - Browser is windowed
 - Navigate to https://imgix.github.io/drift/
 - Mouseover zoom pane (works)
 - Go full screen
 - Mouseover zoom pane (doesn't work)

**Notes:**
 - Also works in reverse (starting full screen and going to windowed mode)
 - I've attempted a workaround by destroying the drift instance and re-initializing it, but it only works within a setTimeout call.

**Comment by dw2** [comment] 2016-06-10 21:41
Also note that this appears to only be an issue with Chrome. Safari 9.1.1 and Firefox 47 both work as expected.

**Comment by paulstraw** [comment] 2016-06-13 18:54
Hey @dw2, this seems to be a regression of some sort with Chrome 51. Have you noticed anywhere else that mouse events work oddly? There are no errors in the console, it just appears to be not firing most mouse events for some reason. This is a tricky one to debug.

**Comment by dw2** [comment] 2016-06-13 23:23
I haven't. Though sometimes I can click+drag in the zoom pane and it will fix itself.

**Comment by paulstraw** [comment] 2016-06-13 23:57
Yeah, I'm seeing that same behavior. Hmmm. I'm going to let this percolate in my head for a bit and see if a solution springs to mind. Right now I'm at a bit of a loss.

**Comment by paulstraw** [comment] 2016-07-08 00:56
Alright, so I was playing with this a bit more @dw2, and noticed that I can resolve the issue (even across page refreshes) by simply moving my mouse up to the top of the screen once to make the address bar and tabs appear. Make any sense to you?

http://paul.st/gf6F

**Comment by dw2** [comment] 2016-07-21 15:49
@paulstraw Yeah, I've seen that same behavior. It seems like mouse events in general are getting out of whack when going to/from fullscreen. I haven't had any luck finding a workaround.

**Comment by paulstraw** [comment] 2016-09-26 21:01
This appears to be a Chrome issue that's unfortunately out of my hands. You can even replicate this behavior on Amazon pages with the hover zoom functionality (down to the "move the mouse to the top" trick to fix it). Closing this.

**Closed by paulstraw** 2016-09-26 21:01 UTC
