### ISSUE TITLE
safari: strange inline pane cuts in safari

### ISSUE THREAD

**Issue by thomas-obernberger** [imgix/drift#236] opened 2019-04-20 19:06 UTC
safari does not display the image in the zoom pane right. after the bigger zoom image is loaded, the image is shown but mostly cut at different heights
i provided an example to reproduce it and screenshots of it. i already tried to fix that, but i had no idea.. it seems like safari does not display the transformed image fully...

**Reproduce**
try this in safari
clearing cache makes it easier
fastest way: start at the top and move the cursor to the bottom of the image
https://codepen.io/studio-08-thomas/pen/GLGrKN

**Screenshots**
![image](https://user-images.githubusercontent.com/20873706/56461129-f3114c80-63ad-11e9-9338-cd7ecd22a03a.png)
![image](https://user-images.githubusercontent.com/20873706/56461109-9f066800-63ad-11e9-9902-3917c9aaf998.png)
![image](https://user-images.githubusercontent.com/20873706/56461206-1688c700-63af-11e9-972b-151ef00579e7.png)

**Expected behaviour**
the image should not be fully visible

**Information:**

- drift version: 1.3.3 / 1.3.4 (have not tried other versions)
- browser version: safari 12.1 & safari tp 12.2

**Additional context**
works in all other major browser (did not tested it in ie/edge so far)
thanks for the great stuff - its really nice to see and great to use :)

**Comment by sherwinski** [comment] 2019-08-29 23:08
Hey @thomas-obernberger sorry for the silence on this issue so far, it's taken a few tries but I finally have some updates.

First to address the inline cuts, I noticed that the overlay image used in your example has `Content-Disposition: attachment` in its response header. I suspect that might be why in _some_ cases the inline cuts occur, as it may [interact strangely](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#As_a_response_header_for_the_main_body) with safari depending on how it handles those requests. In this [codepen](https://codepen.io/sherwinski/pen/VwZWRKy), I've included a similar example using imgix images and can see that the same issue does not occur. So I suspect that by changing where you request your images from, you may be able to avoid this issue.

Incidentally, this issue also highlighted a different bug caused by [webkit not firing `load` events](https://stackoverflow.com/a/5024181) on second hover, causing the "loading" animation that can be seen on the cut out portion of the image. I'll be working on a fix for this shortly.

**Comment by thomas-obernberger** [comment] 2019-08-29 23:52
Hey @sherwinski !

nothing to be sorry about. i am actually happy you got a sight on it and providing me feedback.
Thank you for this information. It's pretty useful and i am looking forward for the patch!

a small offtopic question: is there a convenient way to change the zoom factor immediately without having to hack the mouseenter/mousemove events? (for example: manually handled mousewheel zoom or touch gestures) -> should i create a new issue out of it? (that would be a nice feature)

**Comment by sherwinski** [comment] 2019-08-31 04:15
If I understand your question correctly, no I don't think there is a convenient way to change the zoom factor on the fly. But I agree that would be a cool feature! Please feel free to open a new issue for it, thanks.

**Closed** 2019-09-06 21:44 UTC
